### ISSUE TITLE
option to export table to excel incl. color coding of text

### ISSUE THREAD

**Issue by werkstattcodes** [kcuilla/reactablefmtr#19]
What would be very helpful is an option to export a table to excel. In my specific use case, I am trying to export a table which excludes text columns with some highlighted keywords. As far as I know, there is currently no way to get a table exported to excel and keep e.g. the color coding of specific words. I also couldn't find any workaround via the html export. Many thanks again.

**Comment by kcuilla** [comment]
You can use the {downloadthis} package [https://cran.r-project.org/web/packages/downloadthis/vignettes/downloadthis.html](url) to add a button that allows you to download datasets used in reactable tables to Excel. However, it'll just show the raw data and not any color coding, etc. I believe there is a way to download the dataset with the html styles applied but it's messy since it shows you the entire output of the code that was used to generate the feature. I don't think this is something that can be done simply, at least on my end.
