### ISSUE TITLE
Adding this repo to crosstable widgets 

### ISSUE THREAD

**Issue by DataStrategist** [kcuilla/reactablefmtr#37]
In order to be listed [here](https://rstudio.github.io/crosstalk/widgets.html), you can submit a PR request [here](https://github.com/rstudio/crosstalk/blob/main/docs/widgets.Rmd). 

I would have loved to use this for my last crosstalk project!

**Comment by kcuilla** [comment]
Hi, it's actually already compatible with crosstalk, it's just not listed on the crosstalk site. Here's an example within the cookbook: https://kcuilla.github.io/reactablefmtr/articles/reactablefmtr_cookbook.html#user-interactivity

As far as adding it to the site, I think it would be better to add the reactable package instead since it's the "parent" package. Reactablefmtr is just an extension of reactable.

Thanks for using the package!
