### ISSUE TITLE
Prettier alignment with data_bars_gradient, when values are of different text length

### ISSUE THREAD

**Issue by domsle** [kcuilla/reactablefmtr#7]
Hello,

When running:
```
data <- MASS::Cars93[20:49, c("Make", "MPG.city", "MPG.highway")]
data$MPG.city[1:3] <- data$MPG.city[1:3] + 10^(1:3) # Just lets add 10, 100 and 1000 to first 3 rows

reactable(data,
          columns = list(
              MPG.city = colDef(cell = data_bars_gradient(data))))
```
This results in table show below:
![image](https://user-images.githubusercontent.com/18559095/117011435-20f43000-acee-11eb-881f-4d31f5c50432.png)

Unfortunately, when values in table are of different length, the bar starts from different position. Is there any way to make it more aesthetically pleasing?

**Comment by kcuilla** [comment]
Hi, if you add the following to your column, it'll properly align the values:
style = list(fontFamily = "monospace", whiteSpace = "pre")

More info here:
https://kcuilla.github.io/reactablefmtr/articles/data_bars.html#aligning-values-2

![image](https://user-images.githubusercontent.com/17436783/117033693-9cdf7f80-acd0-11eb-996d-9f393d238956.png)

**Comment by domsle** [comment]
Thank you for the reply, somehow I have missed this section. Also, there is a newer version, not published yet that contains much more options to align labels. 
Thanks :)

**Comment by abraver** [comment]
I'm having a similar issue, which is not resolved with the whitespace="pre"/monospace font.

This issue is actually visible on the "position text" example on [this page](https://kcuilla.github.io/reactablefmtr/articles/data_bars.html).  In the screenshot, you'll notice that the bar for 82% (Pct 1, row 2) is almost the same length as the bar for 68%, when it should be a good bit shorter.

![Screen Shot 2021-08-09 at 7 49 23 PM](https://user-images.githubusercontent.com/2888701/128791940-6d84ad47-6768-4593-8cec-867f11f45522.png)

Adding the whitespace="pre"/monospace font bits, the problem persists.  In this example, I changed some of the values in Pct1 to illustrate the problem more clearly.  As you'll see in the screenshot below, the bar for 90% is actually longer than the bar for 100%!

```{r}
data <- data.frame(
  Group = c("Red Group 1","Red Group 2","Red Group 3","Red Group 4","Red Group 5",
            "Blue Group 1","Blue Group 2","Blue Group 3","Blue Group 4","Blue Group 5",
            "Green Group 1","Green Group 2","Green Group 3","Green Group 4","Green Group 5"),
  Pct1 = c(.9, 1.0, .44, .68, .78, 
           .74, .66, .33, .23, .11, 
           .50, .55, .40, .70, .60),
  Long1 = rep("this is a long string to make everything spread out", 15)
)

  
reactable(
  data,
  pagination = FALSE,
  columns = list(
  Pct1 = colDef(
    style = list(whiteSpace = "pre", fontFamily = "monospace"),
    cell = data_bars(data, fill_color = "lightblue", text_position = "outside-end", number_fmt = scales::percent)
  ))
)

```

![Screen Shot 2021-08-09 at 7 51 37 PM](https://user-images.githubusercontent.com/2888701/128792118-d5933277-22c9-4e68-a2ea-41be961f1ff0.png)

**Comment by kcuilla** [comment]
This is due to the length of the text next to the data bars being wider than the available free space between the value and the maximum value of that column. There are a couple ways to correct this within data_bars():

- One would be to increase the maximum value of the column with max_value. An example of that can be seen here: https://kcuilla.github.io/reactablefmtr/articles/data_bars.html#set-a-maximum-width

- Another would be to change the position of the text. If you set text_position to either "outside-base", "inside-base", "center", or "inside-end", the bars should show as their true length as they won't have to compete with the text for space.

As I'm writing this out, I think I will change the default value of text_position from "outside-end" to "inside-end" so that extra work isn't needed to get the bars to show as their true lengths. Thanks for bringing this to light.
